def very_bad_libs():
    from time import sleep
    student = input("Enter your dream job\n")
    bracelets = input("Enter a plural jewellery\n")
    blouse = input("Enter a piece of clothing\n")
    bite = input("Enter a verb\n")
    insecure = input("Enter an adjective for a person\n")
    Faulkner = input("Enter the name of a genre\n")
    Stephen_king = input("Enter the name of a author\n")
    good = input("Enter a positive adjective\n")

    print("\n\n\n\nWell, hello there. Who are you?")
    sleep(3) 
    print("Based on your vibe, a ",student,". Your ",blouse," is loose.",sep="")
    sleep(3) 
    print("You're not here to be ogled, but those ",bracelets,", they jangle.",sep="")
    sleep(3) 
    print("You like a little attention. Okay, I ",bite,". You search the books.",sep="")
    sleep(2) 
    print("Uh, fiction. ",sep="")
    sleep(2)
    print("F through K...",sep="")
    sleep(2)
    print("Now...",sep="")
    sleep(2)
    print("hmm...",sep="")
    sleep(2)
    print("you're not the standard ",insecure," nymph hunting for a ",Faulkner," you'll never finish.",sep="")
    sleep(3)
    print("Too sun-kissed for ",Stephen_king,". Who will you buy?",sep="")
    sleep(1)
    print(".",sep="")
    sleep(1)
    print(".",sep="")
    sleep(1)
    print(".",sep="")
    sleep(2)
    print('\x1B[3mSorry...\x1B[0m')
    sleep(2)
    print("\n\nYou sound apologetic, like you're embarrassed to be a ",good," girl.")
    sleep(3)
    print("\nAnd you murmur your first word to me."+"\n"+"\n" )
    sleep(3)   
    print('\x1B[3mHello\x1B[0m')
    sleep(5)
    print("\n\n")
def main():
    very_bad_libs()
main()