def very_bad_libs():
    from time import sleep

    name = input("\n\n\n\nWell, hello there. Who are you?\n")
    print("Hi, ",name,". Pleased to meet you.",sep="")
    sleep(2)
    good_bad= input("Would you call yourself more bad or good?\n")
    print("okay, okay... I like that")
    sleep(2)   
    input("How about we get to know each other a little more?\n")
    print("That was quick.",sep="")
    sleep(3)
    print("You like a little attention. Okay...\n",sep="")
    sleep(2)
    print("I'll bite.\n",sep="")
    sleep(1) 
    reading_preference= input("What do you like to read?\n")
    print("Oh? ",sep="",end="")
    sleep(2)
    print("I didn't take you for one of those...",sep="")
    sleep(2)
    print(reading_preference,sep="",end="")
    print('\x1B[3m hmmm...\x1B[0m')
    sleep(2)
    liking= input("could you tell me what you like about those category of books?\n")
    sleep(1)
    print('\x1B[3m so you',"'",'re one of those\x1B[0m',sep="")
    sleep(2)
    print(".",sep="")
    sleep(1)
    print(".",sep="")
    sleep(1)
    print(".",sep="")
    sleep(2)  
    print("Too sun-kissed for Stephen King, too bored of Rowling, and a ", '\x1B[3mparticular\x1B[0m'," fascination for ", reading_preference,sep="")
    sleep(4)
    input("Ever considered reading 'sea of thieves'?")
    sleep(2)
    print("You really should give it a read. I'm sure you'd like it.")
    sleep(4)   
    input("I really hope you read it someday. How about you add it to your tbr?")
    sleep(2)
    print("that's my",good_bad,"girl")
    sleep(2)
    print("I'm sorry but I have to go now.")
    sleep(2)
    print("I'll think of you.")
    sleep(2)
    print("Bye.")
    sleep(4)
    print("<3")
    sleep(3)
    print("  ")
    print("  ")
    print("  ")
def main():
    very_bad_libs()
main()